language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-23.0.3
    - android-24
    - extra-android-support
    - extra

script:
  - ./gradlew clean
  - ./gradlew org.eclipse.paho.android.service:assemble
